
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [LA_BASE] = LAYOUT_61_ansi(
        MA_LMOUSE, KC_LCTL, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS, KC_DEL,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, FR_CIRC, MA_REBOOT, MA_CAPSLOCK,
        MA_LPINKY, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
        MA_NONE, KC_LALT, MA_LTHUMB, KC_SPC, MO(LA_RTHUMB), KC_RALT, KC_RGUI, KC_RCTL
    ),
    [LA_CAPSLOCK] = LAYOUT_61_ansi(
        KC_TRNS, KC_TRNS, S(KC_E), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, S(KC_E), KC_TRNS, S(KC_C), S(KC_Q), KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, S(KC_Q), S(KC_W), S(KC_E), S(KC_R), S(KC_T), S(KC_Y), S(KC_U), S(KC_I), S(KC_O), S(KC_P), FR_CIRC, KC_TRNS, KC_TRNS,
        KC_TRNS, S(KC_A), S(KC_S), S(KC_D), S(KC_F), S(KC_G), S(KC_H), S(KC_J), S(KC_K), S(KC_L), S(KC_SCLN), S(KC_U), KC_TRNS,
        KC_TRNS, S(KC_Z), S(KC_X), S(KC_C), S(KC_V), S(KC_B), S(KC_N), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_MOUSE] = LAYOUT_61_ansi(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_MS_BTN3, KC_MS_BTN1, MA_MS_BTN1_TAP, MA_MS_BTN2_TAP, KC_TRNS, KC_TRNS, KC_MS_BTN4, MA_MS_UP, KC_MS_BTN5, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, MA_MS_WH_UP, MA_MS_WH_DOWN, KC_TRNS, KC_TRNS, KC_TRNS, MA_MS_LEFT, MA_MS_DOWN, MA_MS_RIGHT, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MA_MS_WH_UP, KC_MS_BTN2, MA_MS_WH_DOWN, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, MA_LTHUMBMS, MA_MS_BTN1_TAP, MA_MS_BTN1_HOLD, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LPINKY] = LAYOUT_61_ansi(
        KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, MA_MUTE_KEYS,
        KC_TRNS, KC_UP, KC_BSPC, KC_DEL, MA_JUMPTAB, G(KC_T), KC_TRNS, FR_7, FR_8, FR_9, FR_EQL, FR_ASTR, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_ESC, C(KC_S), KC_ENT, MA_DELLINE, G(KC_G), FR_DOT, FR_4, FR_5, FR_6, FR_MINS, FR_PLUS, KC_ENT,
        KC_TRNS, KC_SCROLL_LOCK, G(KC_X), G(KC_C), G(KC_V), KC_TRNS, FR_0, FR_1, FR_2, FR_3, FR_SLSH, KC_RSFT,
        MA_NONE, KC_TRNS, KC_TRNS, KC_SPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_RTHUMB] = LAYOUT_61_ansi(
        KC_TRNS, FR_AMPR, MA_TILD, FR_HASH, MA_BACKTICK, FR_EURO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, FR_LBRC, FR_RBRC, FR_LCBR, FR_RCBR, FR_AT, FR_MICR, KC_TRNS, KC_PSCR, KC_SCRL, KC_INS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, FR_LABK, FR_RABK, FR_LPRN, FR_RPRN, FR_PIPE, FR_SECT, KC_PSLS, KC_AUDIO_MUTE, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, KC_TRNS, KC_TRNS,
        KC_TRNS, FR_DEG, FR_PERC, FR_DLR, FR_SUP2, FR_PND, KC_PPLS, KC_PMNS, KC_MEDIA_PLAY_PAUSE, KC_TRNS, KC_TRNS, KC_RSFT,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMBESTRONG] = LAYOUT_61_ansi(
        MA_NONE, LAG(KC_1), LAG(KC_2), LAG(KC_3), LAG(KC_4), LAG(KC_5), LAG(KC_6), BT_HST1, BT_HST2, BT_HST3, BT_HST4, BT_HST5, BT_HST6, LAG(KC_BSLS),
        LAG(KC_TAB), LAG(KC_U), LAG(KC_I), LAG(KC_QUOT), LAG(KC_O), LAG(KC_T), LAG(KC_Y), LAG(KC_F1), LAG(KC_F2), LAG(KC_F3), LAG(KC_P), LAG(KC_LBRC), KC_TRNS, MA_NONE,
        KC_TRNS, LAG(KC_H), LAG(KC_J), LAG(KC_SLSH), LAG(KC_K), LAG(KC_G), LAG(KC_F4), LAG(KC_F5), LAG(KC_F6), LAG(KC_L), LAG(KC_F7), LAG(KC_F11), LAG(KC_ENT),
        KC_TRNS, LAG(KC_M), LAG(KC_DOT), LAG(KC_COMM), LAG(KC_SCLN), LAG(KC_B), LAG(KC_N), LAG(KC_F8), LAG(KC_F9), LAG(KC_F10), LAG(KC_F12), MA_NONE,
        MA_NONE, KC_TRNS, KC_TRNS, MA_SUPER, KC_TRNS, KC_TRNS, MA_NONE, MA_NONE
    ),
    [LA_LTHUMBDSTRONG] = LAYOUT_61_ansi(
        MA_NONE, LSA(KC_1), LSA(KC_2), LSA(KC_3), LSA(KC_4), LSA(KC_5), LSA(KC_6), LSA(KC_7), LSA(KC_8), LSA(KC_9), LSA(KC_0), LSA(KC_MINS), LSA(KC_EQL), LSA(KC_BSLS),
        LSA(KC_TAB), LSA(KC_U), LSA(KC_I), LSA(KC_QUOT), LSA(KC_O), LSA(KC_T), LSA(KC_Y), LSA(KC_F1), LSA(KC_F2), LSA(KC_F3), LSA(KC_P), LSA(KC_LBRC), KC_TRNS, MA_NONE,
        KC_TRNS, LSA(KC_H), LSA(KC_J), LSA(KC_SLSH), LSA(KC_K), LSA(KC_G), LSA(KC_F4), LSA(KC_F5), LSA(KC_F6), LSA(KC_L), LSA(KC_F7), LSA(KC_QUOT), LSA(KC_ENT),
        KC_TRNS, LSA(KC_M), LSA(KC_DOT), LSA(KC_COMM), LSA(KC_SCLN), LSA(KC_B), LSA(KC_N), LSA(KC_F8), LSA(KC_F9), LSA(KC_F10), LSA(KC_SLSH), MA_NONE,
        MA_NONE, KC_TRNS, KC_TRNS, MA_SUPER, KC_TRNS, KC_TRNS, MA_NONE, MA_NONE
    ),
    [LA_LTHUMB] = LAYOUT_61_ansi(
        KC_TRNS, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TAB, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, MA_LTHUMBE, G(KC_E), KC_TRNS, KC_TRNS, KC_HOME, KC_UP, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, C(KC_Z), KC_AUDIO_MUTE, MA_LTHUMBD, KC_LGUI, KC_TRNS, KC_BSPC, KC_LEFT, KC_DOWN, KC_RGHT, KC_DEL, KC_TRNS, KC_TRNS,
        KC_LSFT, A(KC_F4), KC_MEDIA_PLAY_PAUSE, G(KC_D), KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_APP, KC_PGDN, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMBMS] = LAYOUT_61_ansi(
        MA_NONE, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TAB, KC_MS_BTN3, KC_MS_BTN1, MA_LTHUMBE, G(KC_E), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, C(KC_Z), KC_AUDIO_MUTE, MA_LTHUMBD, KC_LGUI, KC_TRNS, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS, KC_TRNS,
        KC_TRNS, A(KC_F4), KC_MEDIA_PLAY_PAUSE, G(KC_D), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMB1WEAK] = LAYOUT_61_ansi(
        KC_TRNS, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, C(A(KC_4)), C(A(KC_5)), C(A(KC_6)), C(A(KC_7)), C(A(KC_8)), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, C(A(KC_U)), C(A(KC_I)), MA_LTHUMBE, C(A(KC_O)), C(A(KC_T)), C(A(KC_Y)), KC_TRNS, KC_TRNS, KC_TRNS, C(A(KC_P)), C(A(KC_LBRC)), KC_TRNS, KC_TRNS,
        KC_TRNS, C(A(KC_H)), C(A(KC_J)), MA_LTHUMBD, C(A(KC_K)), C(A(KC_G)), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, C(A(KC_M)), C(A(KC_DOT)), C(A(KC_COMM)), C(A(KC_SCLN)), C(A(KC_B)), C(A(KC_N)), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMB2WEAK] = LAYOUT_61_ansi(
        KC_TRNS, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, RCS(KC_4), RCS(KC_5), RCS(KC_6), RCS(KC_7), RCS(KC_8), RCS(KC_9), RCS(KC_0), RCS(KC_MINS), RCS(KC_EQL), KC_TRNS,
        KC_TRNS, RCS(KC_U), RCS(KC_I), MA_LTHUMBE, RCS(KC_O), RCS(KC_T), RCS(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, RCS(KC_P), RCS(KC_LBRC), KC_TRNS, KC_TRNS,
        KC_TRNS, RCS(KC_H), RCS(KC_J), MA_LTHUMBD, RCS(KC_K), RCS(KC_G), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, RCS(KC_M), RCS(KC_DOT), RCS(KC_COMM), RCS(KC_SCLN), RCS(KC_B), RCS(KC_N), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMB3WEAK] = LAYOUT_61_ansi(
        KC_TRNS, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, LALT(KC_4), LALT(KC_5), LALT(KC_6), LALT(KC_7), LALT(KC_8), LALT(KC_9), LALT(KC_0), LALT(KC_MINS), LALT(KC_EQL), KC_TRNS,
        KC_TRNS, LALT(KC_U), LALT(KC_I), MA_LTHUMBE, LALT(KC_O), LALT(KC_T), LALT(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, LALT(KC_P), LALT(KC_LBRC), KC_TRNS, KC_TRNS,
        KC_TRNS, LALT(KC_H), LALT(KC_J), MA_LTHUMBD, LALT(KC_K), LALT(KC_G), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, LALT(KC_M), LALT(KC_DOT), LALT(KC_COMM), LALT(KC_SCLN), LALT(KC_B), LALT(KC_N), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMBEWEAK] = LAYOUT_61_ansi(
        KC_TRNS, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, LSG(KC_4), LSG(KC_5), LSG(KC_6), LSG(KC_7), RGB_MOD, RGB_VAI, RGB_HUI, RGB_SAI, RGB_SPI, RGB_TOG,
        KC_TRNS, C(KC_V), C(KC_C), MA_LTHUMBE, C(KC_R), LSG(KC_T), LSG(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, LSG(KC_H), C(KC_X), MA_LTHUMBD, C(KC_F), LSG(KC_G), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, LSG(KC_M), LSG(KC_DOT), LSG(KC_COMM), LSG(KC_SCLN), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMBDWEAK] = LAYOUT_61_ansi(
        KC_TRNS, MA_LTHUMB1, MA_LTHUMB2, MA_LTHUMB3, RSG(KC_4), RSG(KC_5), RSG(KC_6), RSG(KC_7), RGB_RMOD, RGB_VAD, RGB_HUD, RGB_SAD, RGB_SPD, BAT_LVL,
        KC_TRNS, MA_WIN_LEFT, MA_WIN_RIGHT, MA_LTHUMBE, RSG(KC_O), RSG(KC_T), RSG(KC_Y), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, C(KC_W), S(C(KC_W)), MA_LTHUMBD, RSG(KC_K), RSG(KC_G), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, RSG(KC_M), KC_PRINT_SCREEN, RSG(KC_COMM), RSG(KC_SCLN), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMBEMO] = LAYOUT_61_ansi(
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MA_UPX4, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MA_BSPCX4, MA_LEFTX4, MA_DOWNX4, MA_RIGHTX4, MA_DELX4, KC_TRNS, MA_ENTX4,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LA_LTHUMBDMO] = LAYOUT_61_ansi(
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MA_UPX2, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MA_BSPCX2, MA_LEFTX2, MA_DOWNX2, MA_RIGHTX2, MA_DELX2, KC_TRNS, MA_ENTX2,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        MA_NONE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS
    ),
};
